version: '3.0'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    ports:
      - 8080:80
    environment:
      - NGINX_HOST=translyaptor.com
    volumes:
      - ./.docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf:rw
      - ./.docker/nginx/logs:/var/log/nginx:rw
      - .:/var/www/html
    networks:
      - web
      - default

  app:
    image: app
    container_name: app
    depends_on:
      - mysql
    build:
      context: ./.docker/php
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.137.1 remote_enable=1 idekey=PHPSTORM"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

networks:
  web:
    external: true
